# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf140126714e497bc58ff18d90a63ba7ee08c617eaaf12d818fdef80aa8b98cb3440240732440593a45c09b64283070d950b34ae3a23816757afd183591e715

test:
  secret_key_base: 498b4bf87401222986e299d3136be5c9ec6ac86c61e4fbba275300496f33a224cdfa02657e609e6b5cce85e0707b5167195d882a03cb371a8774ac04d489c37b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
